# .github/workflows/deploy-image-builder.yml
name: Deploy AWS Image Builder

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-1
  STACK_NAME: image-builder-stack

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install pyyaml boto3
      
      - name: Generate CloudFormation template
        run: |
          python scripts/generate-template.py
      
      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template --template-body file://generated-template.yml
      
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file generated-template.yml \
            --stack-name ${{ env.STACK_NAME }} \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              VpcId=${{ secrets.VPC_ID }} \
              SubnetId=${{ secrets.SUBNET_ID }} \
              InstanceProfileArn=${{ secrets.INSTANCE_PROFILE_ARN }}
      
      - name: Get stack outputs
        run: |
          aws cloudformation describe-stacks \
            --stack-name ${{ env.STACK_NAME }} \
            --query 'Stacks[0].Outputs' \
            --output table
